# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 11:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sacco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nat_id', models.IntegerField(null=True, unique=True)),
                ('telephone', models.IntegerField(null=True, unique=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='ownerProfile/')),
                ('sacco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sacco.Sacco')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=200, null=True)),
                ('capacity', models.IntegerField(null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='owner.Owner')),
                ('sacco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sacco.Sacco')),
            ],
        ),
    ]
