# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 11:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sacco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('registration_no', models.CharField(blank=True, max_length=10)),
                ('office_location', models.CharField(blank=True, max_length=200)),
                ('office_telephone', models.CharField(blank=True, max_length=200)),
                ('office_email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, upload_to='sacco_logo/')),
                ('details', models.CharField(blank=True, max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Super_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=8, unique=True)),
                ('sacco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sacco.Sacco')),
            ],
        ),
    ]
